### ISSUE TITLE
Design Enums

### ISSUE THREAD

**Issue by Baggz** [apiaryio/attributes-kit#126]

**Comment by admorphit** [comment]
Would be great if we could support the following
```
- status (enum[string], optional)
    Show status of widget.
    - Default: `null`
    - Members
        - `null` - Let system determine status.
        - `on` - Widget should be on.
        - `off` - Widget should be off.
```

**Comment by Baggz** [comment]
@admorphit 

With the recent releases of the Attributes Kit this should be supported.

![image](https://cloud.githubusercontent.com/assets/95191/15853102/0416cbde-2ca4-11e6-92ac-134b24074b9f.png)

Feel free to let me know if you have any troubles getting it to work, thanks!

**Comment by Baggz** [comment]
Just a note—enums are supported from version 0.11.

**Comment by admorphit** [comment]
Well done @Baggz and team, looks great.
