### ISSUE TITLE
Provide a minified version of the build without React

### ISSUE THREAD

**Issue by Baggz** [apiaryio/attributes-kit#162]

**Comment by XVincentX** [comment]
Now I remember why I did not provide minified builds for no-react and no-deps

My point was (and still is): if you’re requiring one of those versions (`no-react` and `no-deps`) it means for sure that you’re not going to just drop the code and use it (you need other dependencies). It means you’ll need to plug that file into your own build pipeline, which, regardless of the tool, will complain (at least, both webpack and jspm do) when it encounters minified files.

**Comment by XVincentX** [comment]
Per discussion (basically the reasons above are shared), we won't provide the minified builds.
