### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/attributes-kit#190]
We're missing a changelog. Let's create one and let's keep it up to date.

**Comment by Baggz** [comment]
@XVincentX 

Do you think https://github.com/apiaryio/attributes-kit/releases is not enough?

**Comment by XVincentX** [comment]
I would prefer to keep the changelog within the repo,as [react-router](https://github.com/rackt/react-router/blob/master/CHANGES.md)

**Comment by Baggz** [comment]
Sticking with https://github.com/apiaryio/attributes-kit/releases for now.
