### ISSUE TITLE
Long Attribute Names Wrapping

### ISSUE THREAD

**Issue by jamesdixon** [apiaryio/attributes-kit#203]
Hi, apologies if this issue has already been posted, but couldn't find anything related. Long attribute names are currently wrapping, which can make things a bit difficult to read. Example:

![image](https://cloud.githubusercontent.com/assets/110114/13096276/7530f50a-d4d5-11e5-949b-7f8ffef69878.png)

It appears a `max-width` of `100px` is set on the attribute name column, which causes this. Even on mobile, it appears that there's enough room to give these columns some room to grow.

Cheers,
James

**Comment by Baggz** [comment]
Hi James!

Thanks a lot for reporting this! I'll try to figure out what can be done.

**Comment by Baggz** [comment]
Hi, @jamesdixon!

We have deployed several improvements to Apiary and this shouldn't be happening anymore. If you are still experiencing the issue, feel free to reopen the issue, always happy to help! 🎈
