### ISSUE TITLE
Content of array on resource is rendered as empty

### ISSUE THREAD

**Issue by klokane** [apiaryio/attributes-kit#225]
There is problem with following blueprint:
```
# API Name

## R [GET /r]

+ Response 200 (application/json)
    + Attributes (object)
        + categories (array[Category], required)

# Data Structures

## Category
+ id: 5 (number, required)
+ name: abc (string, required)
```

You can not see content of array
![2016-03-21-174915_1600x900_scrot](https://cloud.githubusercontent.com/assets/489973/13926600/65b17226-ef8d-11e5-9fd3-d325a5d7899f.png)

**Comment by Baggz** [comment]
Looping @tjerabek in.

**Comment by Baggz** [comment]
@klokane 

Thanks for the report! This has been fixed; please give it a try it in Apiary.

### Preview

![image](https://cloud.githubusercontent.com/assets/95191/15855709/52d89fba-2cb1-11e6-9a88-b950f23c5f34.png)

**Comment by klokane** [comment]
:+1:
