### ISSUE TITLE
Boolean with explicit `false` is not correctly rendered

### ISSUE THREAD

**Issue by klokane** [apiaryio/attributes-kit#227]
For following blueprint is not shown `false` value while explicitly specified:

```
# TESTR

## R [GET /r]

+ Response 200 (application/json)
    + Attributes (object)
        + categories (Category)

# Data Structures

## Category
+ m1: `true`  (boolean)
+ m2: `false` (boolean)
```

Actual state:
![2016-03-30-174310_1600x900_scrot](https://cloud.githubusercontent.com/assets/489973/14148254/0744f604-f69f-11e5-8520-aad136a7e90a.png)

Expected behavior is show `false` value in same way as `true`

**Comment by Baggz** [comment]
Thanks, @klokane! I'll take care of that.

**Comment by Baggz** [comment]
@klokane 

This has been fixed in 0.18 Beta 7 release which will be deployed to Apiary in about an hour.

**Comment by klokane** [comment]
:+1:

**Comment by kylef** [comment]
I can confirm this is fixed, closing this issue.

```apib
## Category
+ m1: `true`  (boolean)
+ m2: `false` (boolean)
+ m3 (boolean)
```

![Screenshot 2019-06-13 at 18 35 37](https://user-images.githubusercontent.com/44164/59454470-11be1d80-8e0a-11e9-9b74-e836c188c726.png)
