### ISSUE TITLE
Styles: scroll bar doesn't scroll the action pane

### ISSUE THREAD

**Issue by pjjr** [apiaryio/attributes-kit#228]
This looks like only a nice to have feature: when displaying action pane (parameters, request and response description), scroll bar in right pane doesn't scroll the page

![image](https://cloud.githubusercontent.com/assets/17746143/14171677/6fdf3d1a-f734-11e5-9e48-2022238718c1.png)

_Windows 10, Chrome 49.0.2623.87 m_

**Comment by Baggz** [comment]
Ah, thanks, @pjjr, for the report! I'll try to investigate.

**Comment by patricksmms** [comment]
This works as described with [ApiaryUI](https://blog.apiary.io/ApiaryUI) (v4).
