### ISSUE TITLE
Principle of least privilege for components

### ISSUE THREAD

**Issue by XVincentX** [apiaryio/attributes-kit#23]
We're passing quite often more data than needed for rendering components.

Example

```jsx
        <div className="attributeObjectMemeberKey">
          <KeyComponent data={this.props.data} />
        </div>

        <div className="attributeObjectMemeberRequirement">
          <RequirementComponent data={this.props.data} />
        </div>
```

Both of them do not need the entire data object.

**Comment by Baggz** [comment]
I believe this is no longer relevant; it turned out passing a Refract element into a component is quite handy.

**Comment by XVincentX** [comment]
I think so, the attributes kit is now totally different compared to the one when that issue was opened.

**Comment by Baggz** [comment]
@XVincentX 

Agree.
