### ISSUE TITLE
Using “Include” inside an array

### ISSUE THREAD

**Issue by stanch** [apiaryio/attributes-kit#240]
Would be nice if this was possible:

```md
## Animals
- animals (array)
    - Include Dog
    - Include Cat

## Dog
- says: woof

## Cat
- says: meow
```

Or this:
```md
## Animals
- animals (array)
    - (object)
        - Include Dog
    - (object)
        - Include Cat

## Dog
- says: woof

## Cat
- says: meow
```

Or maybe I’m missing an existing way to do it?

**Comment by Baggz** [comment]
@stanch 

Hey! Thanks for reporting the issue!

The first example won't work as you are trying to include object properties as array items. Sorry about that! We are working hard to improve the overall experience of MSON; e.g. now you get a warning in the Apiary API Editor when you do this.

![image](https://cloud.githubusercontent.com/assets/95191/15856894/b12bcd60-2cb8-11e6-9dbd-2781b4c44dea.png)

The last example, on the other hand, works correctly. 🎉 I just tried it in Apiary and renders as expected.

![image](https://cloud.githubusercontent.com/assets/95191/15856964/ffe4e162-2cb8-11e6-8f61-60423faab564.png)

Feel free to reopen the issue if there's anything else you would like to discuss.

Thanks!
