### ISSUE TITLE
Mixin content is not in place

### ISSUE THREAD

**Issue by klokane** [apiaryio/attributes-kit#243]
for following blueprint:

```
# TESTR

## R [GET /r]

+ Response 200 (application/json)
    + Attributes (Element)

# Data Structures

## Embed
+ One

## Element
+ m1: v1
+ Include Embed
+ m2: v2
```

I expect attributes in order:

```
- m1
- One
- m2
```

In current implementation is content of Mixin placed before all attributes

![2016-05-02-155343_1600x900_scrot](https://cloud.githubusercontent.com/assets/489973/14956086/3e07db7c-107e-11e6-8c27-79b07ef28025.png)

**Comment by Baggz** [comment]
Thanks for the issue, @klokane!

I'm not able to reproduce it in the [Playground](https://attributes-kit.herokuapp.com/),...

![image](https://cloud.githubusercontent.com/assets/95191/14956345/9407ec46-107f-11e6-869c-777377ebb600.png)

...have to look into the integration of the Attributes Kit in Apiary, I'll keep you updated.

**Comment by klokane** [comment]
@Baggz you can see it there
http://docs.testr3.apiary.io/#reference/0/r/r

**Comment by patricksmms** [comment]
This works well with [ApiaryUI](https://blog.apiary.io/ApiaryUI) (v4):
![image](https://user-images.githubusercontent.com/17434816/86930778-ac854a80-c137-11ea-9d1d-d355110d0d27.png)
