### ISSUE TITLE
Attributes Kit does not render samples for an element

### ISSUE THREAD

**Issue by kylef** [apiaryio/attributes-kit#250]
Example structure:

``` apib
# Data Structures
## Example
- message (string)
  - sample
    Hello World
```

Is rendered as the following:

<img width="387" alt="screen shot 2016-05-12 at 14 31 34" src="https://cloud.githubusercontent.com/assets/44164/15231147/47858136-184e-11e6-8c11-35b520c4ef4f.png">

The sample value "Hello World" is not shown.

<img width="289" alt="screen shot 2016-05-12 at 14 32 14" src="https://cloud.githubusercontent.com/assets/44164/15231169/602541ea-184e-11e6-8476-86e8c4af46ec.png">

**Comment by patricksmms** [comment]
This works well with [ApiaryUI](https://blog.apiary.io/ApiaryUI) (v4):
![image](https://user-images.githubusercontent.com/17434816/86930453-557f7580-c137-11ea-8b14-45bf06c76904.png)
