### ISSUE TITLE
Rendering on One Of

### ISSUE THREAD

**Issue by arosenber** [apiaryio/attributes-kit#304]
It's hard to do a search for "One Of". My problem is that there  doesn't seem to be support for rendering references. So for example in the following

```
# Data Structures

## Base1
+ bat

## Base2
+ chimp

## Poly
+ One Of
    + base1 (Base1)
    + base2 (Base2)
    + Properties
        + str1
            + substr1
            + substr2
        + str2
```

It gets displayed by mentioning the Complex Type only, which is kind of weird without a common objects section possible. 

<img width="653" alt="screen shot 2016-07-24 at 11 08 17 pm" src="https://cloud.githubusercontent.com/assets/5505029/17091921/8c920bf8-51f3-11e6-978f-682636f66506.png">

Am I just doing this wrong? Currently I'm getting the basic idea through enum support, but the One Of is much clearer to view. 

Apologies if this is the wrong repo, wasn't very clear which one owned the rendering. Thanks in advance for any help.

**Comment by kylef** [comment]
I can confirm this, I am seeing the same. Here's a full example to reproduce:

```
# My API

## GET /user

+ Response 200 (application/json)
    + Attributes
        + One Of
            + user (User)
            + userId (number)

## Data Structures

### User

+ name: Doe
```

It is being rendered as:

![Screenshot 2019-04-02 at 08 06 17](https://user-images.githubusercontent.com/44164/55382731-53833b80-551e-11e9-9ac9-2bc272d67958.png)

Attributes Kit is rendering "User" as the first one of value, there is no explanation of what User is, or what is inside User in the entire rendered documentation.

**Comment by patricksmms** [comment]
This works well on [ApiaryUI](https://blog.apiary.io/ApiaryUI) (v4):
![image](https://user-images.githubusercontent.com/17434816/86926652-9cb73780-c132-11ea-9ea4-1305c1527a16.png)
