### ISSUE TITLE
Attributes Kit is not able to render the ‘category’ element

### ISSUE THREAD

**Issue by tyrsius** [apiaryio/attributes-kit#339]
I am using [drafter.js](https://github.com/apiaryio/drafter.js) to produce a refract element. Even with a minimal result, like this one

```json
{
        "element": "category",
        "meta": {
            "classes": ["api"],
            "title": "API"
        },
        "attributes": {
            "meta": [{
                "element": "member",
                "meta": {
                    "classes": ["user"]
                },
                "content": {
                    "key": {
                        "element": "string",
                        "content": "FORMAT"
                    },
                    "value": {
                        "element": "string",
                        "content": "1A"
                    }
                }
            }]
        },
        "content": [{
            "element": "copy",
            "content": "# Retail Core JustEnough Integration"
        }]
    }
```

Attribute-kit renders with an error: `Attributes Kit is not able to render the ‘category’ element`
Am I missing something? Is my refract element invalid, or does Attribute-kit not support this model?

**Comment by Baggz** [comment]
Hi @tyrsius!

Attributes Kit currently supports only Data Structure Elements (please see http://api-elements.readthedocs.io/en/latest/element-definitions/#data-structure-elements) which translates to `+ Attributes` and `# Data Structures` sections in your API description document.

To render the whole API description document, I would suggest using (1) Apiary, or (2) an opensource tool called [Aglio](https://github.com/danielgtaylor/aglio).

Hope it helps!

**Comment by tyrsius** [comment]
Thank you for the clarification. Neither of those work for me, I need to perform this rendering client-side. Looks like I'll be building my own =(

**Comment by XVincentX** [comment]
@tyrsius  
If I understand correctly, are you trying to render the entire refract tree on the client side?

**Comment by tyrsius** [comment]
Yes

**Comment by XVincentX** [comment]
I see - unfortunately this is not really the right place - but you might be interested in using this kit as part of your project.

I'd love to know the future developments eventually - please keep me posted and do not hesitate do ask for help if some parts of the tree aren't clear!
