### ISSUE TITLE
Nullable attribute isn't rendered

### ISSUE THREAD

**Issue by archmage** [apiaryio/attributes-kit#460]
Hi! First off, I'm sorry if this is not the right place to bring this up; I did a bit of exploring and this seems suitable, but if I'm wrong I apologise.

Now then! I spoke to a colleague and they mentioned that nullable attributes don't show up in the table of attributes. After some research I found [this issue on api-blueprint](https://github.com/apiaryio/api-blueprint/issues/320), which discusses the matter briefly (specifically [this comment](https://github.com/apiaryio/api-blueprint/issues/320#issuecomment-227199733)).

_image taken from comment above; example 2 is nullable_
<img width="322" alt="03ae5098-370f-11e6-8f20-498966db590c" src="https://user-images.githubusercontent.com/4102334/34280521-3e9aa400-e70c-11e7-8b06-17f9f4d4fb1d.png">
 
The comment dates from June 2016, where @kylef mentions that "this is coming"... but it's been a year and a half since and it's not implemented.

**I was wondering if anyone is presently working on this!** If not, I'd like to look into attempting a PR that adds this behaviour.

Can someone advise me as to whether this is a suitable course of action? Thanks in advance!

**Comment by ikendoit** [comment]
Hello Archmage, 
  Sorry to see that no one responded to your issue.
  My team is having a similar problem, we ended up accepting the rendered string `"null"` as a `null` value.

I am interested in knowing what you ended up doing. Did you find a work around ? Or did you move on to another documentation tool ?

**Comment by archmage** [comment]
Hey @ikendoit! Thanks for your interest in this ages-old issue.

I wrote this on behalf of a colleague (as mentioned), who was in a different team at the time. As such, my engagement was mostly of a nature of "I'll solve this if I can, and there's interest!" Unfortunately due to this issue being entirely ignored (though, I expect I'm not the only one given [only two issues have been closed since September 2017](https://github.com/apiaryio/attributes-kit/issues?q=is%3Aissue+is%3Aclosed+sort%3Aupdated-desc)), I never got around to following this up.

I have no clue if this will ever get fixed - I'm not exactly optimistic - but in the event that I ever have to use an API-documenting tool, it'll likely be one that's a little more active in the "engaging with community issues" department, I'm afraid!

Best of luck with your team's project! 🙂

**Comment by Almad** [comment]
@archmage @ikendoit We do apologize for missing this one out :(  It's true that this repo haven't seen much love, reason being the [significant revamp of the documentation this repository is embedded in](https://blog.apiary.io/ApiaryUI). Work is trickling down, however, and we should be able to provide some love here as well :)

**Comment by patricksmms** [comment]
Hi! I'm are really sorry that you had your questions unanswered for so long. 
The nullable type attribute is now visible, in [ApiaryUI](https://blog.apiary.io/ApiaryUI):
![image](https://user-images.githubusercontent.com/17434816/81840320-1e328500-9549-11ea-9598-d126c68df623.png)
