### ISSUE TITLE
Apiary Blueprint Docs: Text alignment bug on attributes

### ISSUE THREAD

**Issue by foxx** [apiaryio/attributes-kit#479]
As you can see in this screenshot, the attribute description text does not line up with the attribute name or the required/optional status icon.

![screen shot 2015-07-21 at 16 07 44](https://cloud.githubusercontent.com/assets/651797/8804150/b068c28c-2fc2-11e5-84bd-d6306ad40ddf.png)

**Comment by patricksmms** [comment]
This works well on [ApiaryUI](https://blog.apiary.io/ApiaryUI) (v4):
![image](https://user-images.githubusercontent.com/17434816/86927734-fc621280-c133-11ea-8541-e0864c38abce.png)
