### ISSUE TITLE
Apiary Blueprint Docs: Table in data structure definition

### ISSUE THREAD

**Issue by peterpp** [apiaryio/attributes-kit#480]
Table inside data structure has no styling. For example:

```
# Data Structures

## Item
+ `id`: `301` (required) - Item identifier.
+ `state`: `available` (enum) - Actual state of the item.

    Controls listing on web catalogue and availability for purchasing and downloading.

    | State         | Category | Search | Detail | Purchase | Download |
    |:--------------|----------|--------|--------|----------|----------|
    | `public`      | yes      | yes    | yes    |          |          |
    | `pre_order`   | yes      | yes    | yes    | yes      | may 1)   |

```

looks like this:

![screen shot 2016-07-11 at 13 56 20](https://cloud.githubusercontent.com/assets/1448883/16729855/6d96851e-476f-11e6-9213-c7ee01c6a01a.png)

**Comment by patricksmms** [comment]
This works well on [ApiaryUI](https://blog.apiary.io/ApiaryUI) (v4):
![image](https://user-images.githubusercontent.com/17434816/86927037-1a7b4300-c133-11ea-97c8-40de0af47515.png)

**Comment by sinclas** [comment]
How was the "Data Structures" table created above done in Apiary?
