### ISSUE TITLE
Rendering one of with "Include" mixin

### ISSUE THREAD

**Issue by kylef** [apiaryio/attributes-kit#487]
When using a One Of with "Include", the "Include" is being references as a "ref" property, here's an example API Blueprint, see below for a screenshot of how Attributes Kit is rendering this.

```apib
# My API

## GET /user

+ Response 200 (application/json)
    + Attributes
        + One Of
            + user (object)
                + Include User
            + userId (number)

## Data Structures

### User

+ name: Doe

### UserMixin

+ user (User)
```

![Screenshot 2019-04-02 at 08 15 49](https://user-images.githubusercontent.com/44164/55383311-cd67f480-551f-11e9-8ef4-2c08e0affba6.png)

**Comment by patricksmms** [comment]
This works well on ApiaryUI (v4).
