### ISSUE TITLE
Rendering array with samples doesn't render the example structures

### ISSUE THREAD

**Issue by kylef** [apiaryio/attributes-kit#489]
Given the following API Blueprint:

```apib
# My API

## GET /

+ Response 200 (application/json)
    + Attributes (array[AnimalTarget], fixed-type)
        + Sample
            + (AnimalCatTarget)
            + (AnimalDogTarget)

## Data Structures

### AnimalTarget

+ type (required)

### AnimalCatTarget (AnimalTarget)

+ type: cat (fixed)

### AnimalDogTarget (AnimalTarget)

+ type: dog (fixed)
```

The data structures are rendered as:

<img width="687" alt="Screenshot 2019-05-08 at 14 12 54" src="https://user-images.githubusercontent.com/44164/57377880-6d5a1300-719b-11e9-9f76-81a1129f95db.png">

The result shows the two sample "types" (not values) but it doesn't show what the actual contents of those structures.

I've filled a couple of similiar bugs to this before over the last few years, #250 and #446 which are possibly related.

**Comment by patricksmms** [comment]
This works well on ApiaryUI (v4).
