### ISSUE TITLE
Data Structures

### ISSUE THREAD

**Issue by Baggz** [apiaryio/attributes-kit#80]
https://github.com/apiaryio/api-blueprint/blob/master/API%20Blueprint%20Specification.md#data-structures-section

**Comment by schellkenig** [comment]
As discussed with your support having a separate section in the documentation that shows all data structures would be great. Beside that data structures look already very nice in the attributes sections of the calls, nice work!

**Comment by patricksmms** [comment]
This feature was implemented on [ApiaryUI](https://blog.apiary.io/ApiaryUI) (v4).
![image](https://user-images.githubusercontent.com/17434816/86929798-8c08c080-c136-11ea-977c-eb507d45a379.png)
